#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        Na 0.0 0.0 0.0 
        Cl -2.815 -2.815 -2.815 
    End
    Lattice
        0.0 2.815 2.815
        2.815 0.0 2.815
        2.815 2.815 0.0
    End
    BondOrders
         1 2 1.0 0 0 1
         1 2 1.0 0 1 0
         1 2 1.0 0 1 1
         1 2 1.0 1 0 0
         1 2 1.0 1 0 1
         1 2 1.0 1 1 0
    End
End

Engine BAND
    Basis
        Core Small
    End
    XC
        GGA PBE
    End
EndEngine
eor

