#!/bin/bash

#export QE=/data.local1/milias/software/quantum-epresso/q-e-qe-6.5/bin
export QE=/usr/bin

echo -e "\n running $QE \"`hostname`\"  "

 proj=Si.scf_k3x12
 mpirun -np 4 $QE/pw.x < $proj.in > $proj.out

exit 0
