#!/bin/sh

"$AMSBIN/ams" << eor

Task GeometryOptimization
GeometryOptimization
    OptimizeLattice Yes
End
System
    Atoms
        Og 0.0 0.0 0.0 
    End
    Lattice
        0.0 1.805 1.805
        1.805 0.0 1.805
        1.805 1.805 0.0
    End
    BondOrders
         1 1 1.0 -1 -1 0
         1 1 1.0 -1 -1 1
         1 1 1.0 -1 0 -1
         1 1 1.0 -1 0 0
         1 1 1.0 -1 0 1
         1 1 1.0 -1 1 -1
         1 1 1.0 -1 1 0
         1 1 1.0 -1 1 1
         1 1 1.0 0 -1 -1
         1 1 1.0 0 -1 0
         1 1 1.0 0 -1 1
         1 1 1.0 0 0 -1
         1 1 1.0 0 0 1
         1 1 1.0 0 1 -1
         1 1 1.0 0 1 0
         1 1 1.0 0 1 1
         1 1 1.0 1 -1 -1
         1 1 1.0 1 -1 0
         1 1 1.0 1 -1 1
         1 1 1.0 1 0 -1
         1 1 1.0 1 0 0
         1 1 1.0 1 0 1
         1 1 1.0 1 1 -1
         1 1 1.0 1 1 0
    End
End

Engine BAND
    Basis
        Type TZP
        Core None
    End
    NuclearModel Gaussian
    Relativity
        Level Spin-Orbit
    End
    XC
        SpinOrbitMagnetization CollinearZ
        GGA PBEsol
    End
EndEngine
eor

