#!/bin/bash

##------------------------------------------------------------------------------------------------------------
##
##                                  ASE job submission script v11.0
##
##-----------------------------------------Slurm settings-----------------------------------------------------
## jobname
#SBATCH -J ElHg

##  partition (queue)
#SBATCH --account=bltp
#SBATCH --partition=bltp
##SBATCH --constraint=icelake
#SBATCH --constraint=cascade
#SBATCH --qos=long
#SBATCH --distribution=block:block,nopack

# ensure physical-core-only allocation
# 1. Disable hyperthreading (logical cores)
#SBATCH --hint=nomultithread
# 2. Ensure only one task per physical core
#SBATCH --ntasks-per-core=1

## max. execution time
##SBATCH -t 4-00:00:00
##SBATCH -t 0-03:00:00
#SBATCH -t 30-00:00:00

#SBATCH --mem=168GB
##SBATCH --mem-per-cpu=6GB

## nodes
#SBATCH -N 1
##SBATCH --nodelist=n05p028,n05p029
##SBATCH --nodelist=n05p032
#SBATCH --ntasks-per-node=40

## stdout/stderr output file
#SBATCH -o log_slurm_job.%j.%N.std_out_err

## E-mail
#SBATCH --mail-user=dsen@theor.jinr.ru
#SBATCH --mail-type=ALL


##------------------------------------------------------------------------------------------------------------
##
##
##-----------------------------------------Builds with DFT-D4 patch-------------------------------------------
#

echo -e "\nRunning on host `hostname` at `date`"
echo -e "\n The total memory at the main node (in GB)"
free -t -g


#### QE ####
module purge
module load  Python/v3.12.13
#module load  intel/v2025.3.1
echo -e "\nloaded modules:"
module list

source /lustre/projects/m/milias/work/software/myvenv/bin/activate
pip list 
pip show ase

#IntelMPI2026.1 compilers
echo -e "\n\n Activating IntelMPI OneAPI 2026.1 :"
source /lustre/projects/m/milias/work/software/intel/oneapi/setvars.sh

echo -e "\n\n python ? ; python -V :\c"; which python; python -V
echo -e "\n ifx ? ; ifx -V: \c"; which ifx; ifx -V
echo -e "\n mpiifx ? ;  mpiifx -V: \c";which mpiifx; mpiifx -V
echo -e "\n icx ? ; icx -V: \c"; which icx; icx -V
echo -e "\n icpx ? ; icpx -V: \c"; which icpx; icpx -V
echo -e "\n Intel MKL library ? MKLROOT=$MKLROOT"
echo -e "\n mpirun ? \c"; which mpirun; mpirun --version

#export QE="/lustre/projects/m/milias/work/software/quantum-espresso/git_cloned/q-e_cloned/build_intelmpi2026.1_libxc_mkl_scalapack_n05p"
export QE="/lustre/projects/m/milias/work/software/quantum-espresso/git_cloned/q-e_cloned/build_intelmpi2026.1_libxc_mkl_scalapack_n02p"
echo -e "\n\n Checking $QE/bin/pw.x :"
ls -lt  $QE/bin/pw.x
ldd  $QE/bin/pw.x

##--------------------------------------------------------------------------------------------------------------
##
##
##-------------------------------------------Print debug info---------------------------------------------------
echo -e "\n srun --mpi=list :"; srun --mpi=list

echo -e "\nJob user is SLURM_JOB_USER= $SLURM_JOB_USER"
echo -e "User job SLURM_JOB_NAME=$SLURM_JOB_NAME has assigned ID SLURM_JOBID=$SLURM_JOBID"
echo -e "This job was submitted from the computer SLURM_SUBMIT_HOST=$SLURM_SUBMIT_HOST"
echo -e "and from the home directory SLURM_SUBMIT_DIR:"
echo -e "$SLURM_SUBMIT_DIR"

echo -e "Job is running on the cluster compute node: SLURM_CLUSTER_NAME=$SLURM_CLUSTER_NAME"
echo -e "and is employing SLURM_JOB_NUM_NODES=$SLURM_JOB_NUM_NODES node/nodes:"
echo -e "SLURM_JOB_NODELIST = $SLURM_JOB_NODELIST"
echo -e "Job partition is SLURM_JOB_PARTITION=$SLURM_JOB_PARTITION \n"
echo -e "Number of allocated CPUs on each single node, SLURM_CPUS_ON_NODE=$SLURM_CPUS_ON_NODE ."
echo -e "Number of all reserved threads over ALL nodes, SLURM_NTASKS=$SLURM_NTASKS ."
echo -e "Job has reserved memory per node, SLURM_MEM_PER_NODE=$SLURM_MEM_PER_NODE MB of memory"

echo -e "\n\n List of MPI servers :"
srun -l /bin/hostname | sort -n | awk '{print $2}'

# CPU model, total numer of CPUs, number of allocated CPUs
echo -e "\n\nThe node's CPU \c"; cat /proc/cpuinfo | grep 'model name' | uniq
NPROCS=`cat /proc/cpuinfo | grep processor | wc -l`
echo "BTW, this node has total $NPROCS CPUs available for an EXCLUSIVE job."
echo "Based on reserved memory, this node got $SLURM_CPUS_ON_NODE CPUs allocated for SLURM calculations."
echo "This job wants in total SLURM_NTASKS=$SLURM_NTASKS threads . "

echo -e "cpuinfo :"; cpuinfo
echo -e "impi_info :"; impi_info

# for running jobs from your homedir, use ...
cd $SLURM_SUBMIT_DIR

echo -e "\nCurrent directory where this SLURM job is running `pwd`"
echo "It has the disk space of (df -h) :"
df -h .
echo

##--------------------------------------------------------------------------------------------------------------
##
##
##---------------------------------------------------Run job----------------------------------------------------
# Add this line before your main execution to log the binding:
srun --label grep Cpus_allowed_list /proc/self/status

# another summary
#srun taskset -cp $$

## Check physical vs logical IDs
#lscpu -p=CPU,Core,Socket

# try to fix file saving ...
ulimit -a
ulimit -f unlimited

## Specify ASE script here
echo -e "\n\n"
echo -e "\n============================================================"
echo -e "\n"
echo -e "\nStarting ASE parallel job on \c";date; echo

  python electronic_properties.py

echo -e "\nASE finished on : \c";date
exit
##--------------------------------------------------------------------------------------------------------------
