module m
contains
  attributes(global) subroutine increment(a, b)
    implicit none
    integer, intent(inout) :: a(*)
    integer, value :: b
    integer :: i

    i = threadIdx%x
    a(i) = a(i)+b

  end subroutine increment
end module m


program incrementGPU
  use cudafor
  use m
  implicit none
  integer, parameter :: n = 256
  integer :: a(n), b
  integer, device :: a_d(n)

  a = 1
  b = 3

  a_d = a
  call increment<<<1,n>>>(a_d, b)
  a = a_d

  if (any(a /= 4)) then
     print *, '**** Program Failed ****'
  else
     print *, 'Program Passed'
  endif
end program incrementGPU
