#!/bin/bash
 
#SBATCH --job-name="A script which fails, but displays 0 as exit code"
#SBATCH --time=00:05:00
#SBATCH --mem-per-cpu=3G
#SBATCH -p devel
#SBATCH -A m2_him_exp
 
module load lang/R/3.4.1-foss-2017a
 
# Put your code below this line
R --no-save --slave -f fail.r
echo "Script finished"
