program streamSync
  use cudafor
  implicit none
  integer, parameter :: n=100000
  real, device :: a_d(n), b_d(n), c_d(n)
  integer(kind=cuda_stream_kind) :: stream1, stream2, stream3
  integer :: istat, i, j

  istat = cudaStreamCreate(stream1)
  istat = cudaStreamCreate(stream2)
  istat = cudaStreamCreate(stream3)

  !$cuf kernel do <<<1,1,stream=stream1>>>
  do i = 1, n
     a_d(i) = i
  enddo

  !$cuf kernel do <<<1,1,stream=stream2>>>
  do i = 1, n
     b_d(i) = i
  enddo

  !$cuf kernel do <<<1,1,stream=stream3>>>
  do i = 1, n
     c_d(i) = 1.0/i 
  enddo

  istat = cudaStreamSynchronize(stream1)
  
  !$cuf kernel do <<<1,1,stream=stream2>>>
  do i = 1, n
     a_d(i) = a_d(i) + b_d(i)
  enddo

  istat = cudaStreamDestroy(stream1)
  istat = cudaStreamDestroy(stream2)
  istat = cudaStreamDestroy(stream3)
end program streamSync
