#!/bin/bash

##------------------------------------------------------------------------------------------------------------
##
##                                  ASE job submission script v11.0
##
##-----------------------------------------Slurm settings-----------------------------------------------------
## jobname
#SBATCH -J ElHg

##  partition (queue)
#SBATCH --account=bltp
#SBATCH --partition=bltp
##SBATCH --constraint=icelake
#SBATCH --constraint=cascade
#SBATCH --qos=long
#SBATCH --distribution=block:block,nopack

# ensure physical-core-only allocation
# 1. Disable hyperthreading (logical cores)
#SBATCH --hint=nomultithread
# 2. Ensure only one task per physical core
#SBATCH --ntasks-per-core=1

## max. execution time
##SBATCH -t 4-00:00:00
##SBATCH -t 0-03:00:00
#SBATCH -t 30-00:00:00

#SBATCH --mem=168GB

##SBATCH --mem-per-cpu=6GB
##SBATCH --mem-per-cpu=3GB

## nodes
#SBATCH -N 1
##SBATCH --nodelist=n05p032
#SBATCH --ntasks-per-node=40

## stdout/stderr output file
#SBATCH -o log_slurm_job.%j.%N.std_out_err

## E-mail
#SBATCH --mail-user=dsen@theor.jinr.ru
#SBATCH --mail-type=ALL


echo -e "\nRunning on host `hostname` at `date`"
echo -e "\nThe total memory at the main node (in GB)"
free -t -g

#### QE ####
module purge
module load  Python/v3.12.13
module load  openmpi/v4.1.8_gcc1230
echo -e "\n\nloaded modules:"
module list

source /lustre/projects/m/milias/work/software/myvenv/bin/activate
echo -e "\n\n pip installed stuff:"
pip list 
pip show ase

echo -e "\n\n initiating MKL 2026.1 :"
source /lustre/projects/m/milias/intel_mkl/oneapi/setvars.sh

echo -e "\n\n Python ? :\c"; which python; python -V
echo -e " mpif90 ? \c"; which mpif90; mpif90 --version
echo -e " mpicc ? \c";  which mpicc; mpicc --version
echo -e " mpicxx ? \c"; which mpicxx; mpicxx --version
echo -e " mpirun ? \c"; which mpirun; mpirun --version
echo -e "\n Intel MKL library ? MKLROOT=$MKLROOT"


#export PMIX_MCA_gds=hash
#export PMIX_MCA_psec=none
#export OMPI_MCA_btl=^openib

# Reduce verbosity
#export PMIX_MCA_pmix_base_verbose=0
#export OMPI_MCA_orte_base_help_aggregate=0

echo -e "\n\n Simple mpirun checks: "
# Test with hostname
mpirun -np 4 hostname
# Test with a simple MPI program
mpirun -np 4 echo "Hello"

export QE="/lustre/projects/m/milias/work/software/quantum-espresso/git_cloned/q-e_cloned/build_openmpi4.1.8_gcc12.3.0_mkl2026.1_scalapack_libxc"
echo -e "\n\n Checking $QE/bin/pw.x ..."
ls -lt $QE/bin/pw.x
ldd  $QE/bin/pw.x

##--------------------------------------------------------------------------------------------------------------
##
##
##-------------------------------------------Print debug info---------------------------------------------------
echo -e "\n\n srun --mpi=list :"; srun --mpi=list

echo -e "\nJob user is SLURM_JOB_USER= $SLURM_JOB_USER"
echo -e "User job SLURM_JOB_NAME=$SLURM_JOB_NAME has assigned ID SLURM_JOBID=$SLURM_JOBID"
echo -e "This job was submitted from the computer SLURM_SUBMIT_HOST=$SLURM_SUBMIT_HOST"
echo -e "and from the home directory SLURM_SUBMIT_DIR:"
echo -e "$SLURM_SUBMIT_DIR"

echo -e "Job is running on the cluster compute node: SLURM_CLUSTER_NAME=$SLURM_CLUSTER_NAME"
echo -e "and is employing SLURM_JOB_NUM_NODES=$SLURM_JOB_NUM_NODES node/nodes:"
echo -e "SLURM_JOB_NODELIST = $SLURM_JOB_NODELIST"
echo -e "Job partition is SLURM_JOB_PARTITION=$SLURM_JOB_PARTITION \n"
echo -e "Number of allocated CPUs on each single node, SLURM_CPUS_ON_NODE=$SLURM_CPUS_ON_NODE ."
echo -e "Number of all reserved threads over ALL nodes, SLURM_NTASKS=$SLURM_NTASKS ."
echo -e "Job has reserved memory per node, SLURM_MEM_PER_NODE=$SLURM_MEM_PER_NODE MB of memory"

echo -e "\n\n List of MPI servers :"
srun -l /bin/hostname | sort -n | awk '{print $2}'

# CPU model, total numer of CPUs, number of allocated CPUs
echo -e "\n\nThe node's CPU \c"; cat /proc/cpuinfo | grep 'model name' | uniq
NPROCS=`cat /proc/cpuinfo | grep processor | wc -l`
echo "BTW, this node has total $NPROCS CPUs available for an EXCLUSIVE job."
echo "Based on reserved memory, this node got $SLURM_CPUS_ON_NODE CPUs allocated for SLURM calculations."
echo "This job wants in total SLURM_NTASKS=$SLURM_NTASKS threads . "

echo -e "\n\ncpuinfo :"; cpuinfo
echo -e "\n ompi_info :"; ompi_info

# for running jobs from your homedir, use ...
cd $SLURM_SUBMIT_DIR

echo -e "\n\nCurrent directory where this SLURM job is running `pwd`"
echo "It has the disk space of (df -h) :"
df -h .
echo

##--------------------------------------------------------------------------------------------------------------
##
##
##---------------------------------------------------Run job----------------------------------------------------
# Add this line before your main execution to log the binding:
#srun --label grep Cpus_allowed_list /proc/self/status

# another summary
#srun taskset -cp $$

## Check physical vs logical IDs
#lscpu -p=CPU,Core,Socket

# try to fix file saving ...
ulimit -a
ulimit -f unlimited

## Specify ASE script here
echo -e "\n\n"
echo -e "\n============================================================"
echo -e "\n"
echo -e "\nStarting ASE parallel job on \c";date; echo

python electronic_properties.py

echo -e "\nASE finished on : \c";date
exit
##--------------------------------------------------------------------------------------------------------------
