#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        Cs 0.0 0.0 0.0 
        Pb 2.86903158999455 2.86903158999455 2.86903158999455 
        Br 2.86903158999455 -0.0 2.86903158999455 
        Br 2.86903158999455 2.86903158999455 0.0 
        Br -0.0 2.86903158999455 2.86903158999455 
    End
    Lattice
        5.73806317 0.0 0.0
        0.0 5.73806317 0.0
        0.0 0.0 5.73806317
    End
    BondOrders
         1 3 1.0
         1 3 1.0 -1 0 -1
         1 3 1.0 -1 0 0
         1 3 1.0 0 0 -1
         1 4 1.0
         1 4 1.0 -1 -1 0
         1 4 1.0 -1 0 0
         1 4 1.0 0 -1 0
         1 5 1.0
         1 5 1.0 0 -1 -1
         1 5 1.0 0 -1 0
         1 5 1.0 0 0 -1
         2 3 1.0
         2 3 1.0 0 1 0
         2 4 1.0
         2 4 1.0 0 0 1
         2 5 1.0
         2 5 1.0 1 0 0
    End
End

Engine BAND
    Basis
        Type TZP
    End
    BZPath
        Path
            0.0  0.0   0.0   G
            0.5  0.0   0.0   X
            0.5  0.5   0.0   M
            0.5  0.5   0.5   R
            0.0  0.0   0.0   G
        End
    End
    BandStructure
        Enabled Yes
        Automatic No
        DeltaK 0.02
    End
    Dependency
        Core 0.8
    End
    DOS
        CalcPDOS Yes
        StoreCoopPerBasPair Yes
    End
    Relativity
        Level Spin-Orbit
    End
    SCF
        PrintAllOccupiedBands Yes
    End
    XC
        SpinOrbitMagnetization CollinearZ
        GGA PBEsol
    End
    StrainDerivatives
        Subtractatomicxc Yes
    End
EndEngine
eor

