program peakBandwidth
  use cudafor
  implicit none

  integer :: i, istat, nDevices=0
  type (cudaDeviceProp) :: prop

  istat = cudaGetDeviceCount(nDevices)
  do i = 0, nDevices-1
     istat = cudaGetDeviceProperties(prop, i)
     print "(' Device Number: ',i0)", i
     print "('   Device name: ',a)", trim(prop%name)
     print "('   Memory Clock Rate (KHz): ', i0)", &
          prop%memoryClockRate
     print "('   Memory Bus Width (bits): ', i0)", &
          prop%memoryBusWidth
     print "('   Peak Memory Bandwidth (GB/s): ', f9.2)", &
          2.0 * prop%memoryClockRate * &
          (prop%memoryBusWidth / 8) * 1.e-6
     print *
  enddo
end program peakBandwidth
