#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
PESPointCharacter
    Tolerance 0.02
End
System
    Atoms
        P -0.0 0.0 -0.158938 adf.R=1.850
        O -1.376202 -0.345026 0.5308850000000001 adf.R=1.517
        O 0.986903 -1.019313 0.5308850000000001 adf.R=1.517
        O 0.3893 1.364339 0.5308850000000001 adf.R=1.517
        O -0.0 0.0 -1.624986 adf.R=1.517
        H -2.139809 0.013909 0.06375699999999999 adf.R=1.350
        H 1.057859 -1.860083 0.06375699999999999 adf.R=1.350
        H 1.08195 1.846175 0.06375699999999999 adf.R=1.350
    End
    BondOrders
         1 2 1.0
         1 3 1.0
         1 4 1.0
         1 5 2.0
         2 6 1.0
         3 7 1.0
         4 8 1.0
    End
End

Engine ADF
    Basis
        Type TZ2P-J
        Core None
    End
    Save TAPE10
    XC
        GGA OPBE
    End
    Relativity
        Level None
    End
    Symmetry NOSYM
    Solvation
        Surf Delley
        Solv name=Chloroform cav0=0.0 cav1=0.0067639
        Charged method=CONJ
        C-Mat POT
        SCF VAR ALL 
        CSMRSP
    End
    NumericalQuality Good
EndEngine
eor

# =======
# NMR NMR
# =======

cp "${AMS_RESULTSDIR-${AMS_JOBNAME-ams}.results}/adf.rkf" TAPE21
cp "${AMS_RESULTSDIR-${AMS_JOBNAME-ams}.results}/TAPE10" TAPE10

"$AMSBIN/nmr" << eor
NMR
    out    iso    tens
    adfgui
    Atoms 1 
    u1k best
    calc all
End

eor

mv TAPE21 "${AMS_RESULTSDIR-${AMS_JOBNAME-ams}.results}/adf.rkf"
rm -f TAPE10 TAPE15


# ===
# CPL
# ===

cp "${AMS_RESULTSDIR-${AMS_JOBNAME-ams}.results}/adf.rkf" TAPE21

"$AMSBIN/cpl" << eor
NMRCOUPLING
  fc 
ADFGUI
END
eor

mv TAPE21 "${AMS_RESULTSDIR-${AMS_JOBNAME-ams}.results}/adf.rkf"


