#!/bin/sh

export AMS_RESULTSDIR="$SCM_RESULTDIR/$JOBNAME.results/lead.results"
mkdir -p "$AMS_RESULTSDIR"
export lead="$AMS_RESULTSDIR/band.rkf"
#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        Au.1 0.0 0.0 0.0 
        Au.2 2.9 0.0 0.0 
        Au.3 5.8 0.0 0.0 
    End
    Lattice
        8.699999999999999 0.0 0.0
    End
End

Engine BAND
    Title  Leads Tight Binding
    KSpace
        Quality VeryGood
    End
    Relativity
        Level Scalar
    End
    SoftConfinement
        Quality Basic
    End
    StoreHamiltonian2 Yes
    XC
        LDA SCF VWN
    End
EndEngine
eor
export AMS_RESULTSDIR="$SCM_RESULTDIR/$JOBNAME.results/scattering.results"
mkdir -p "$AMS_RESULTSDIR"
export scattering="$AMS_RESULTSDIR/band.rkf"
#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        Au.1L -20.3 0.0 0.0 
        Au.2L -17.4 0.0 0.0 
        Au.3L -14.5 0.0 0.0 
        Au.C -11.6 0.00000000 0.00000000 
        Au.C -8.699999999999999 0.00000000 0.00000000 
        Au.C -5.799999999999999 0.00000000 0.00000000 
        Au.C -2.899999999999999 0.00000000 0.00000000 
        Au.C 0.0 0.00000000 0.00000000 
        Au.C 2.9 0.00000000 0.00000000 
        Au.C 5.799999999999999 0.00000000 0.00000000 
        Au.C 8.700000000000001 0.00000000 0.00000000 
        Au.C 11.6 0.00000000 0.00000000 
        Au.1R 14.5 0.0 0.0 
        Au.2R 17.4 0.0 0.0 
        Au.3R 20.3 0.0 0.0 
    End
    Lattice
        43.5 0.0 0.0
    End
End

Engine BAND
    Title  Scattering Region
    Relativity
        Level Scalar
    End
    SoftConfinement
        Quality Basic
    End
    StoreHamAsMol Yes
    StoreHamiltonian2 Yes
    XC
        LDA SCF VWN
    End
EndEngine
eor
$AMSBIN/conductance <<EOF
EnergyGrid min=-3.5 max=3 num=200
Files
  Leads $lead
  Scattering $scattering
End

EOF

cp "$scattering" negf.rkf
$AMSBIN/cpkf ConductanceResults.kf negf.rkf "results --rename NEGF"
rm ConductanceResults.kf

